// Code generated by SdkContractGenerator. DO NOT EDIT.

export const contract = {
  "remove-background": {
    "models": [
      "recraft-remove-background"
    ],
    "fields_by_model": {
      "recraft-remove-background": {
        "source_image_url": {
          "required": true
        }
      }
    }
  },
  "upscale-image": {
    "models": [
      "recraft-crisp-upscale"
    ],
    "fields_by_model": {
      "recraft-crisp-upscale": {
        "source_image_url": {
          "required": true
        }
      }
    }
  }
} as const;
